version: '3'
services:
  server:
    container_name: backend_express_project3
    build: 
      context: ../project3-backend
    ports:
      - "3338:3338"
    environment:
      LANG: C.UTF-8
    volumes:
      - ../project3-backend:/usr/src/backend
    stdin_open: true
    tty: true
    depends_on:
      - db
  frontend:
    container_name: frontend_project3
    build: 
      context: ../project3-frontend
    volumes:
      - ../project3-frontend:/usr/src/frontend
    stdin_open: true
    tty: true
    ports:
      - "3003:3003"
    links:
      - server
  db: 
    container_name: db_express_pro3
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: "social_network"
    ports:
      - "3309:3306"
  
